name: Java - Build CI (no tests + Spotless)

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build (no tests) + Spotless
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Setup Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean and build (skip tests)
        run: ./gradlew clean build -x test --no-daemon

      - name: Spotless check
        run: ./gradlew spotlessCheck --no-daemon
