name: Java - Artifact (Docker)

on:
  workflow_call:
    inputs:
      runner:
        description: 'The type of machine to run the job on'
        required: false
        type: string
        default: 'ubuntu-latest'
      version:
        description: 'Version to tag the Docker image (e.g. 1.2.3)'
        required: true
        type: string

jobs:
  artifact:
    name: Docker Image
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker image
        run: docker build -t ${{ github.repository }}:${{ inputs.version }} .
